build_and_deploy:
    stage: build
    script:
        - npm install
        - npm run build
        - git log --oneline --decorate > ./build/_h5ai/CHANGELOG.txt
        - cd ./build/
        - scp -r . root@dose.rsc.lan:/var/www/
    environment: staging